#!/bin/bash


diskused=$( df -h | grep "/dev/sda1" | awk '{print $5}' ) # Uses the df command to look at space used in /dev/sda1
memfree=$( free -mh | grep Mem: | awk '{print $7}' )      # Uses the free command to tell us how much RAM we have unsude on the system
connections=$( netstat | grep tcp )                       # Lists alll active tcp connections from and to our machine
users=$( who | awk '{print $1}' )                         # Lists all users currently logged in

echo -en "This is a snapshot of your current system:
	
		\e[34m	Disk Used: $diskused
		\e[36m	Free Memory: $memfree
		\e[92m	Logged in Users: $users

\e[96mOpen Internet Connections:
$connections
\e[39m
"

echo "
color info:
http://misc.flogisoft.com/bash/tip_colors_and_formatting
http://wiki.bash-hackers.org/scripting/style
https://help.ubuntu.com/community/UnityLaunchersAndDesktopFiles
"

